### REQUIRED ###
APPLICATION_NAME: ad1-lead-main
BUSINESS_NAME: administrasi
SERVER_NAME: https://adira.co.id
TEMPLATE: maven
TESTING_TAG: uat

jenkins:
  # Arbitrary / Dynamic
  CREDENTIAL_HELM: kubeconfig
  JAR_APP_NAME: com.admengine-0.0.1-SNAPSHOT.jar
  LINK_SONARQUBE: http://10.161.17.144:9000/dashboard?id=
  NAMESPACE: leadengine
  SONARQUBE_KEY: alksfhoqhqhfijv0w9320582358flkshal
  SONARQUBE_URL: http://10.50.0.2:9000

docker:
  # Arbitrary / Dynamic
  ELASTIC_PORT: 8200
  ELASTIC_URL: apm-server.logging.svc.cluster.local
  JAR_ELASTIC: elastic-apm-agent-1.28.1
  JAR_SNAPSHOT: id-0.0.1-snapshot

helm:
  # Arbitrary / Dynamic
  BUILD_NUMBER: 1
  BUILD_TIMESTAMP: 220331
  CPU_LIMIT: 2500m
  CPU_REQUEST: 250m
  DB_PASSWORD: root
  DB_USER: root
  MEM_LIMIT: 2048Mi
  MEM_REQUEST: 256Mi
  SECRETDB_NAME: regcred
  SERVICE_PORT: 443
  SERVICE_TARGETPORT: 8081
  SERVICE_TYPE: LoadBalancer
  Version_Major: 1
  Version_Minor: 0
  Version_Patch: 0
