### REQUIRED ###
APPLICATION_NAME: ad1-lead-main
BUSINESS_NAME: administrasi
TESTING_TAG: uat
SERVER_NAME: https://adira.co.id
TEMPLATE: maven

jenkins:
  # Arbitrary / Optional / Dynamic
  LINK_SONARQUBE: http://10.161.17.144:9000/dashboard?id=
  SONARQUBE_URL: http://10.50.0.2:9000
  SONARQUBE_KEY: alksfhoqhqhfijv0w9320582358flkshal
  JAR_APP_NAME: com.admengine-0.0.1-SNAPSHOT.jar
  CREDENTIAL_HELM: kubeconfig

docker:
  # Arbitrary / Optional / Dynamic
  JAR_SNAPSHOT: id-0.0.1-snapshot
  JAR_ELASTIC: elastic-apm-agent-1.28.1
  ELASTIC_URL: APM-SERVER.logging.svc.cluster.local
  ELASTIC_PORT: 8200

helm:
  # Arbitrary / Optional / Dynamic
  Version_Major: 1
  Version_Minor: 0
  Version_Patch: 0
  BUILD_TIMESTAMP: 220331
  BUILD_NUMBER: 1
  TYPE_SERVICE: LoadBalancer
  SERVICE_PORT: 443
  SERVICE_TARGETPORT: 8081
  CPU_LIMIT: 2500m
  MEM_LIMIT: 2048Mi
  CPU_REQUEST: 250m
  MEM_REQUEST: 256Mi
  DB_USER:
  DB_PASSWORD:
  secret_name:
