jenkins:
  file: Jenkinsfile-uat
  imageName: index.docker.io/cocatrip/halo
  imageTag: latest
  buildContainer: node

helm:
  file: helm/ad1-lead-main/values-uat.yaml
  imageRepository: repo.repo
  imageTag: latest
