app: ad1-lead-main
businessName: administrasi
tag: uat
template: maven

jenkins:
  SERVER_NAME: https://adira.co.id
  LINK_SONARQUBE: http://10.161.17.144:9000/dashboard?id=
  SONARQUBE_URL: http://10.50.0.2:9000
  SONARQUBE_KEY: alksfhoqhqhfijv0w9320582358flkshal
  JAR_APP_NAME: com.admengine-0.0.1-SNAPSHOT.jar
  CREDENTIAL_HELM: kubeconfig

docker:
  JAR_SNAPSHOT: id-0.0.1-snapshot
  JAR_ELASTIC: elastic-apm-agent-1.28.1
  ELASTIC_URL: apm-server.logging.svc.cluster.local
  ELASTIC_PORT: 8200
